### ISSUE TITLE
Support for Paypal website payment pro

### ISSUE THREAD

**Issue by mpoiriert** [Payum/Payum#375]
I am trying to migrate a existing payment system to Payum. I thought I was using Paypal Payment Pro but in fact I am using Paypal Website Payment Pro:

https://developer.paypal.com/webapps/developer/docs/classic/paypal-payments-pro/integration-guide/WPWebsitePaymentsPro/

From what I see it's not integrated in payum ?

**Comment by makasim** [comment]
Not it is not, but looking quickly at the docs you posted the website payment pro is based on paypal express checkout and paypal pro and simply means that user can select two method, and as far as I see it does not require coding.

**Comment by elvismdev** [comment]
I'm confused with so many Paypal payment options... In order to create a web checkout experience where customers do not have to leave the website to complete and place an order. I'll would have to use Payum with [Paypal Pro Checkout](https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ProCheckout/Nvp/Resources/docs/index.md) integration. Correct?

**Comment by makasim** [comment]
> I'll would have to use Payum with Paypal Pro Checkout integration. Correct?

Yes, you are right.
