### ISSUE TITLE
payum/payum dev-master requires php-http/client-implementation ^1.0 -> no matching package found.

### ISSUE THREAD

**Issue by analyzer666** [Payum/Payum#514]
subject. no such package exist.

**Comment by makasim** [comment]
Since 1.3 (current master) payum does not rely on Guzzle but instead require a [virtual package](https://devedge.wordpress.com/2014/09/27/composer-and-virtual-packages/)  `php-http/client-implementation`. You have to require one of its implementations: https://packagist.org/providers/php-http/client-implementation
