### ISSUE TITLE
Implement security checker in composer

### ISSUE THREAD

**Issue by liamsorsby** [Payum/Payum#797]
I've just manually run the Symfony vulnerability checker which has found the dev-dependency propel has a potential mysql injection vulnerability. Unfortunately, it doesn't look like there is a fix for propel 1.7.

> Symfony
>
> Security Check Report
> =============================
>
> 1 package has known vulnerabilities.
>
> propel/propel1 (1.7.1)
> ----------------------
>
> * [CVE-NONE-0001][]: SQL injection possible with limit() on MySQL
>
> [CVE-NONE-0001]: https://github.com/propelorm/Propel/issues/1052
>
> Note that this checker can only detect vulnerabilities that are referenced in the security advisories 
> database.
>Execute this command regularly to check the newly discovered vulnerabilities.

**Comment by pierredup** [comment]
Since this project doesn't ship with a `composer.lock` file, there wouldn't be much benefit in using the security checker to check the installed dependencies.
It is up to the applications using this package to ensure they check their `composer.lock` for any installed dependencies that are vulnerable.

The best we can do here is to require roave/security-advisories (as done in #904) to ensure we don't install and test against any vulnerable package.

**Comment by pierredup** [comment]
Fixed in #904
